# Image de base Alpine
ARG VARIANT=latest
# FROM docker.io/library/alpine:${VARIANT}
FROM public.ecr.aws/docker/library/alpine:${VARIANT}
LABEL org.opencontainers.image.description="Image de base"
LABEL org.opencontainers.image.base.name=public.ecr.aws/docker/library/alpine:${VARIANT}

ARG LOCALE=fr-CA
ARG USER=podman

ENV LANG=${LOCALE}.UTF-8

RUN apk update && apk upgrade && \
    apk add --no-cache \
    age age-doc \
    apk-tools-doc \
    fish fish-doc \
    acl acl-doc \
    bat bat-doc bat-fish-completion \
    bind-tools \
    bottom bottom-doc bottom-fish-completion \
    broot broot-doc broot-fish-completion \
    btop btop-doc \
    ca-certificates ca-certificates-doc \
    chezmoi chezmoi-fish-completion \
    curl curl-doc curl-fish-completion \
    dust dust-doc dust-fish-completion \
    dysk \
    eza eza-doc eza-fish-completion \
    fastfetch fastfetch-doc fastfetch-fish-completion \
    fd fd-doc fd-fish-completion \
    fuse-overlayfs \
    gcompat \
    gdu gdu-doc \
    git git-doc git-credential-oauth git-credential-oauth-doc \
    github-cli github-cli-doc github-cli-fish-completion \
    gpg gpg-agent \
    htop htop-doc \
    hyperfine hyperfine-doc hyperfine-fish-completion \
    jq jq-doc \
    lsd lsd-fish-completion \
    man-db man-db-doc man-db-lang \
    man-pages \
    micro micro-doc \
    musl-locales \
    nano nano-doc \
    openssh-client-common \
    openssh-keygen \
    pinentry-curses-ss pinentry-doc \
    podman podman-doc podman-fish-completion \
    podman-remote \
    procs procs-doc procs-fish-completion \
    ripgrep ripgrep-doc ripgrep-fish-completion \
    sudo \
    shadow \
    starship \
    topgrade topgrade-doc topgrade-fish-completion \
    tree tree-doc \
    unzip unzip-doc \
    vim vim-doc vimdiff \
    wget wget-doc \
    wipe wipe-doc \
    xh xh-doc xh-fish-completion \
    yq-go yq-go-fish-completion \
    zip zip-doc

COPY --chmod=644 ["config/fish/conf.d/*", "/etc/fish/conf.d/"]
COPY --chmod=644 ["config/fish/functions/*", "/etc/fish/functions/"]

RUN \
    cd /usr/local/bin && \
    curl https://zyedidia.github.io/eget.sh | sh && chown root:root /usr/local/bin/eget && \
    echo '%wheel ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/wheel-nopasswd && \
    sed -ri 's|^(root:)(.*)/bin/sh|\1\2/usr/bin/fish|' /etc/passwd

RUN \
    /usr/local/bin/eget tealdeer-rs/tealdeer --to /usr/local/bin/ && \
    ln -s /usr/local/bin/tealdeer /usr/local/bin/tldr

RUN \
    useradd --shell /usr/bin/fish ${USER} --groups wheel --create-home && \
    mkdir -p /home/${USER}/.local/share/fish /tmp/storage-run-1000/podman && \
    chown ${USER}:${USER} -R /home/${USER} /tmp/storage-run-1000

VOLUME /tmp/storage-run-1000/podman/

USER ${USER}
WORKDIR /home/${USER}
CMD [ "/usr/bin/fish" ]
