version: "3"

vars:
  OWNER: sylchamber
  CLI_OCI: podman
  GHCR:
    map:
      REGISTRY: ghcr.io
      OWNER: sylchamber
  QUAY:
    map:
      REGISTRY: quay.io
      OWNER: sylchambr
  OPS_DOWNLOAD_VOLUME: ops-build-downloads

set: [pipefail]

tasks:
  default:
    desc: Affiche les tâches disponibles
    cmd: task -l

  auth:ghcr:
    desc: S'authentifie au registre GitHub Container Registry
    cmd: |
      echo $GITHUB_TOKEN | {{.CLI_OCI}} login -u {{.GHCR.OWNER}} --password-stdin {{.GHCR.REGISTRY}}

  auth:quay:
    desc: S'authentifie au registre Quay.io
    cmd: |
      echo $QUAY_CLI_PASSWORD | {{.CLI_OCI}} login -u {{.QUAY.OWNER}} --password-stdin {{.QUAY.REGISTRY}}

  build:all:
    desc: Construit et étiquette toutes les images
    deps: [build:base, build:ops]

  build:almalinux-toolbox:
    desc: Construit et étiquette sylchamber/almalinux-toolbox
    vars:
      IMAGE: almalinux-toolbox
      VARIANT: "9"
    cmd: |
      {{.CLI_OCI}} build \
      -t {{.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.OWNER}}/{{.IMAGE}}:latest \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:latest \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:latest \
      {{.IMAGE}}

  build:almalinux-toolbox-ops:
    desc: Construit et étiquette sylchamber/almalinux-toolbox-ops
    vars:
      IMAGE: almalinux-toolbox-ops
      VARIANT: "9"
    cmd: |
      {{.CLI_OCI}} build \
      -t {{.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.OWNER}}/{{.IMAGE}}:latest \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:latest \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:latest \
      {{.IMAGE}}

  build:base:
    desc: Construit et étiquette sylchamber/base
    requires:
      vars:
        - name: IMAGE
          enum: [base, ops]
        - name: VARIANT
          enum: [alpine]
    vars:
      IMAGE: base
      VARIANT: alpine
    cmd: |
      {{.CLI_OCI}} build \
      -t {{.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.OWNER}}/{{.IMAGE}}:{{.VARIANT}}-latest \
      -t {{.OWNER}}/{{.IMAGE}}:latest \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}}-latest \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:latest \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}}-latest \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:latest \
      {{.IMAGE}}

  build:ops:
    desc: Construit et étiquette l'image sylchamber/ops
    deps: [build-deps:ops]
    requires:
      vars:
        - name: IMAGE
          enum: [base, ops]
        - name: VARIANT
          enum: [alpine]
    vars:
      IMAGE: ops
      VARIANT: alpine
      USER: ops
      DOWNLOADS_PATH:
        sh: |
          {{.CLI_OCI}} volume inspect {{.OPS_DOWNLOAD_VOLUME}} --format {{"'{{.Mountpoint}}'"}}
    cmd: |
      {{.CLI_OCI}} build \
      -t {{.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.OWNER}}/{{.IMAGE}}:{{.VARIANT}}-latest \
      -t {{.OWNER}}/{{.IMAGE}}:latest \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}}-latest \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:latest \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}}-latest \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:latest \
      --build-arg USER={{.USER}} \
      --volume {{.DOWNLOADS_PATH}}:/downloads \
      {{.IMAGE}}

  build-deps:ops:
    desc: Contruit les prérequis à build ops
    cmd: |
      {{.CLI_OCI}} volume create --ignore {{.OPS_DOWNLOAD_VOLUME}}

  push:all:
    desc: Publie toutes les images
    deps: [push:base, push:ops]

  push:almalinux-toolbox:
    desc: Publie l'image sylchamber/almalinux-toolbox
    vars:
      IMAGE: almalinux-toolbox
      VARIANT: "9"
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:almalinux-toolbox-ops:
    desc: Publie l'image sylchamber/almalinux-toolbox-ops
    vars:
      IMAGE: almalinux-toolbox-ops
      VARIANT: "9"
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:base:
    desc: Publie l'image sylchamber/base
    vars:
      IMAGE: base
      VARIANT: alpine
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:ops:
    desc: Publie l'image sylchamber/ops
    vars:
      IMAGE: ops
      VARIANT: alpine
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:*:*:
    desc: Publie l'image spécifiée
    requires:
      vars:
        - name: IMAGE
          enum: [almalinux-toolbox, almalinux-toolbox-ops, base, ops]
        - name: VARIANT
          enum: ["9", alpine]
    vars:
      IMAGE: "{{index .MATCH 0}}"
      VARIANT: "{{index .MATCH 1}}"
    cmds:
      - echo "Publication de l'image {{.REGISTRY}}/{{.OWNER}}/{{.IMAGE}}:{{.VARIANT}}" >&2
      - "{{.CLI_OCI}} push {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}}"
      - "{{.CLI_OCI}} push {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:latest"
      - "{{.CLI_OCI}} push {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}}"
      - "{{.CLI_OCI}} push {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:latest"
