version: "3"

vars:
  OWNER: sylchamber
  CLI_OCI: podman
  GHCR:
    map:
      REGISTRY: ghcr.io
      OWNER: sylchamber
  QUAY:
    map:
      REGISTRY: quay.io
      OWNER: sylchambr

set: [pipefail]

tasks:
  default:
    desc: Affiche les tâches disponibles
    cmd: task -l

  auth:ghcr:
    desc: S'authentifie au registre GitHub Container Registry
    cmd: |
      echo $GITHUB_TOKEN | {{.CLI_OCI}} login -u {{.GHCR.OWNER}} --password-stdin {{.GHCR.REGISTRY}}

  auth:quay:
    desc: S'authentifie au registre Quay.io
    cmd: |
      echo $QUAY_CLI_PASSWORD | {{.CLI_OCI}} login -u {{.QUAY.OWNER}} --password-stdin {{.QUAY.REGISTRY}}

  build:all:
    desc: Construit et étiquette toutes les images
    deps: [build:almalinux-toolbox, build:almalinux-toolbox-ops]

  build:eget:
    desc: Construit et étiquette sylchamber/eget
    vars:
      IMAGE: eget
      VARIANT: latest
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:alpine-tools-shell:
    desc: Construit et étiquette sylchamber/alpine-tools-shell
    vars:
      IMAGE: alpine-tools-shell
      VARIANT: latest
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:alpine-tools-ops:
    desc: Construit et étiquette sylchamber/alpine-tools-ops
    vars:
      IMAGE: alpine-tools-ops
      VARIANT: latest
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:alpine-toolbox:
    desc: Construit et étiquette sylchamber/alpine-toolbox
    vars:
      IMAGE: alpine-toolbox
      VARIANT: latest
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:alpine-toolbox-ops:
    desc: Construit et étiquette sylchamber/alpine-toolbox-ops
    vars:
      IMAGE: alpine-toolbox-ops
      VARIANT: latest
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:almalinux-toolbox:
    desc: Construit et étiquette sylchamber/almalinux-toolbox
    vars:
      IMAGE: almalinux-toolbox
      VARIANT: "10"
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:almalinux-toolbox-ops:
    desc: Construit et étiquette sylchamber/almalinux-toolbox-ops
    vars:
      IMAGE: almalinux-toolbox-ops
      VARIANT: "10"
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:tools-shell:
    desc: Construit et étiquette sylchamber/tools-shell
    vars:
      IMAGE: tools-shell
      VARIANT: latest
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:ubuntu-toolbox:
    desc: Construit et étiquette sylchamber/ubuntu-toolbox
    vars:
      IMAGE: ubuntu-toolbox
      VARIANT: rolling
    cmds:
      - task: build:{{.IMAGE}}:{{.VARIANT}}

  build:*:*:
    internal: true
    desc: Construit l'image spécifiée
    requires:
      vars:
        - name: IMAGE
        - name: VARIANT
    vars:
      IMAGE: "{{index .MATCH 0}}"
      VARIANT: "{{index .MATCH 1}}"
    cmd: |
      {{.CLI_OCI}} build \
      -t {{.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.OWNER}}/{{.IMAGE}}:latest \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:latest \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}} \
      -t {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:latest \
      {{.IMAGE}}

  push:all:
    desc: Publie toutes les images
    deps: [push:almalinux-toolbox, push:almalinux-toolbox-ops]

  push:eget:
    desc: Publie l'image sylchamber/eget
    vars:
      IMAGE: eget
      VARIANT: latest
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:alpine-tools-shell:
    desc: Publie l'image sylchamber/alpine-tools-shell
    vars:
      IMAGE: alpine-tools-shell
      VARIANT: latest
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:alpine-tools-ops:
    desc: Publie l'image sylchamber/alpine-tools-ops
    vars:
      IMAGE: alpine-tools-ops
      VARIANT: latest
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:alpine-toolbox:
    desc: Publie l'image sylchamber/alpine-toolbox
    vars:
      IMAGE: alpine-toolbox
      VARIANT: latest
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:alpine-toolbox-ops:
    desc: Publie l'image sylchamber/alpine-toolbox-ops
    vars:
      IMAGE: alpine-toolbox-ops
      VARIANT: latest
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:almalinux-toolbox:
    desc: Publie l'image sylchamber/almalinux-toolbox
    vars:
      IMAGE: almalinux-toolbox
      VARIANT: "10"
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:almalinux-toolbox-ops:
    desc: Publie l'image sylchamber/almalinux-toolbox-ops
    vars:
      IMAGE: almalinux-toolbox-ops
      VARIANT: "10"
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:tools-shell:
    desc: Publie l'image sylchamber/tools-shell
    vars:
      IMAGE: tools-shell
      VARIANT: latest
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:ubuntu-toolbox:
    desc: Publie l'image sylchamber/ubuntu-toolbox
    vars:
      IMAGE: ubuntu-toolbox
      VARIANT: rolling
    cmds:
      - task: push:{{.IMAGE}}:{{.VARIANT}}

  push:*:*:
    desc: Publie l'image spécifiée
    internal: true
    requires:
      vars:
        - name: IMAGE
        - name: VARIANT
    vars:
      IMAGE: "{{index .MATCH 0}}"
      VARIANT: "{{index .MATCH 1}}"
    cmds:
      - echo "Publication de l'image {{.REGISTRY}}/{{.OWNER}}/{{.IMAGE}}:{{.VARIANT}}" >&2
      - "{{.CLI_OCI}} push {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:{{.VARIANT}}"
      - "{{.CLI_OCI}} push {{.GHCR.REGISTRY}}/{{.GHCR.OWNER}}/{{.IMAGE}}:latest"
      - "{{.CLI_OCI}} push {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:{{.VARIANT}}"
      - "{{.CLI_OCI}} push {{.QUAY.REGISTRY}}/{{.QUAY.OWNER}}/{{.IMAGE}}:latest"
