# Ubuntu latest = LTS
ARG VARIANT=latest
FROM docker.io/library/ubuntu:${VARIANT}
LABEL \
    org.opencontainers.image.description="Image eget pour téléchargement d'outils absents des dépôts" \
    org.opencontainers.image.source=https://github.com/SylChamber/conteneurs \
    org.opencontainers.image.base.name=docker.io/library/ubuntu:${VARIANT}

ARG EGET_VERSION=1.3.4

RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install curl unzip

RUN \
    mkdir -p \
    /etc/bash_completion.d \
    /etc/fish/completions \
    /usr/local/bin \
    /usr/local/share/man/man1

RUN \
    curl -sLo - https://github.com/zyedidia/eget/releases/download/v${EGET_VERSION}/eget-${EGET_VERSION}-linux_amd64.tar.gz | \
    tar xzvf - -C /usr/local/bin/ --strip-components 1 --exclude '*/LICENSE' --exclude '*/README.md' && \
    chown root:root /usr/local/bin/eget* && \
    chmod 755 /usr/local/bin/eget && \
    chmod 644 /usr/local/bin/eget.1 && \
    mv /usr/local/bin/eget.1 /usr/local/share/man/man1/
