# syntax=docker/dockerfile:1.2
ARG VARIANT=latest

ARG BIN_PATH=/usr/local/bin
ARG MAN_PATH=/usr/local/share/man/man1

ARG CHEZMOI_TAG=v2.68.1
ARG GOTASK_TAG=v3.46.4
ARG LYCHEE_TAG=lychee-v0.22.0
ARG RCLONE_TAG=v1.72.1
ARG TOPGRADE_TAG=v16.7.0
ARG TQ_TAG=0.2.2
ARG YQ_TAG=v4.50.1

FROM ghcr.io/sylchamber/eget:${VARIANT} as base

FROM base as chezmoi
ARG BIN_PATH
ARG CHEZMOI_TAG
RUN eget twpayne/chezmoi --asset linux_amd64.tar.gz --asset '^sbom' --tag ${CHEZMOI_TAG} --to ${BIN_PATH}

FROM base as lychee
ARG BIN_PATH
ARG LYCHEE_TAG
RUN eget lycheeverse/lychee --asset gnu --tag ${LYCHEE_TAG} --to ${BIN_PATH}

FROM base as rclone
ARG BIN_PATH
ARG MAN_PATH
ARG RCLONE_TAG
RUN \
    eget rclone/rclone --asset zip --tag ${RCLONE_TAG} --download-only --to /tmp/rclone-${RCLONE_TAG}.zip && \
    unzip -j /tmp/rclone-${RCLONE_TAG}.zip '*/rclone' -d ${BIN_PATH}/ && \
    unzip -j /tmp/rclone-${RCLONE_TAG}.zip '*/rclone.1' -d ${MAN_PATH}/

FROM base as task
ARG BIN_PATH
ARG GOTASK_TAG
RUN eget go-task/task --asset tar.gz --tag ${GOTASK_TAG} --to ${BIN_PATH}

FROM base as topgrade
ARG BIN_PATH
ARG TOPGRADE_TAG
RUN eget topgrade-rs/topgrade --asset gnu --tag ${TOPGRADE_TAG} --to ${BIN_PATH}

FROM base as tq
ARG BIN_PATH
ARG TQ_TAG
RUN eget cryptaliagy/tomlq --asset amd64 --tag ${TQ_TAG} --to ${BIN_PATH}

FROM base as yq
ARG BIN_PATH
ARG MAN_PATH
ARG YQ_TAG
RUN \
    eget mikefarah/yq --asset tar.gz --tag ${YQ_TAG} --download-only --to /tmp/yq-${YQ_TAG}.tar.gz && \
    tar xvf /tmp/yq-${YQ_TAG}.tar.gz -C ${BIN_PATH} --wildcards './yq_linux_amd64' && \
    tar xvf /tmp/yq-${YQ_TAG}.tar.gz -C ${MAN_PATH} --wildcards 'yq.1' && \
    mv ${BIN_PATH}/yq_linux_amd64 ${BIN_PATH}/yq

FROM base as fresh
RUN eget sinelaw/fresh --asset amd64.deb --download-only --to /usr/local/share/

# build final
FROM ghcr.io/sylchamber/eget:${VARIANT}
LABEL \
    org.opencontainers.image.description="Outils shell communs absents des dépôts de certaines distributions" \
    org.opencontainers.image.source=https://github.com/SylChamber/conteneurs \
    org.opencontainers.image.base.name=ghcr.io/sylchamber/eget:${VARIANT}

ARG BIN_PATH
ARG MAN_PATH

COPY --from=chezmoi ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=lychee ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=rclone ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=rclone ${MAN_PATH}/* ${MAN_PATH}/
COPY --from=task ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=topgrade ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=tq ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=yq ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=yq ${MAN_PATH}/* ${MAN_PATH}/
COPY --from=fresh /usr/local/share/*.deb /usr/local/share/
