# syntax=docker/dockerfile:1.2
ARG VARIANT=latest

ARG BIN_PATH=/usr/local/bin
ARG MAN_PATH=/usr/local/share/man

ARG GOTASK_TAG=v3.46.4
ARG TOPGRADE_TAG=v16.7.0
ARG TQ_TAG=0.2.2
ARG YQ_TAG=v4.50.1

FROM ghcr.io/sylchamber/eget:${VARIANT} as base

FROM base as task
ARG BIN_PATH
ARG GOTASK_TAG
RUN eget go-task/task --asset tar.gz --tag ${GOTASK_TAG} --to ${BIN_PATH}

FROM base as topgrade
ARG BIN_PATH
ARG TOPGRADE_TAG
RUN eget topgrade-rs/topgrade --asset gnu --tag ${TOPGRADE_TAG} --to ${BIN_PATH}

FROM base as tq
ARG BIN_PATH
ARG TQ_TAG
RUN eget cryptaliagy/tomlq --asset amd64 --tag ${TQ_TAG} --to ${BIN_PATH}

FROM base as yq
ARG BIN_PATH
ARG MAN_PATH
ARG YQ_TAG
RUN eget mikefarah/yq --asset tar.gz --tag ${YQ_TAG} --file yq_linux_amd64 --to ${BIN_PATH}/yq
RUN eget mikefarah/yq --asset tar.gz --tag ${YQ_TAG} --file yq.1 --to ${MAN_PATH}/man1/

FROM base as fresh
RUN eget sinelaw/fresh --asset amd64.deb --download-only --to /usr/local/share/

# build final
FROM ghcr.io/sylchamber/eget:${VARIANT}
LABEL \
    org.opencontainers.image.description="Outils shell communs absents des dépôts de certaines distributions" \
    org.opencontainers.image.source=https://github.com/SylChamber/conteneurs \
    org.opencontainers.image.base.name=ghcr.io/sylchamber/eget:${VARIANT}

ARG BIN_PATH
ARG MAN_PATH

COPY --from=task ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=topgrade ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=tq ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=yq ${BIN_PATH}/* ${BIN_PATH}/
COPY --from=yq ${MAN_PATH}/man1/* ${MAN_PATH}/man1/
