# Image de base Alpine
ARG VARIANT=latest
# Utilisation du miroir AWS pour éviter les restrictions de Docker Hub
# FROM docker.io/library/alpine:${VARIANT}
FROM public.ecr.aws/docker/library/alpine:${VARIANT}
LABEL org.opencontainers.image.description="Image de base"
LABEL org.opencontainers.image.source=https://github.com/SylChamber/conteneurs
LABEL org.opencontainers.image.base.name=docker.io/library/alpine:${VARIANT}

ARG LOCALE=fr-CA
ARG EGET_VERSION=1.3.4
ARG TLDR_TAG=v1.8.1

ENV LANG=${LOCALE}.UTF-8

RUN \
    apk update && apk upgrade && \
    apk add --no-cache \
    fish fish-doc \
    age age-doc \
    apk-tools-doc \
    acl acl-doc \
    bat bat-doc bat-fish-completion \
    bind-tools bind-doc \
    bottom bottom-doc bottom-fish-completion \
    broot broot-doc broot-fish-completion \
    btop btop-doc \
    ca-certificates ca-certificates-doc \
    chezmoi chezmoi-fish-completion \
    containers-common-doc \
    curl curl-doc curl-fish-completion \
    dust dust-doc dust-fish-completion \
    dysk \
    eza eza-doc eza-fish-completion \
    fastfetch fastfetch-doc fastfetch-fish-completion \
    fd fd-doc fd-fish-completion \
    fuse-overlayfs \
    gcompat \
    gdu gdu-doc \
    git git-doc git-credential-oauth git-credential-oauth-doc \
    github-cli github-cli-doc github-cli-fish-completion \
    gpg gpg-agent \
    htop htop-doc \
    hyperfine hyperfine-doc hyperfine-fish-completion \
    jq jq-doc \
    lsd lsd-fish-completion \
    man-db man-db-doc man-db-lang \
    man-pages \
    micro micro-doc \
    musl-locales \
    nano nano-doc \
    openssh-client-common \
    openssh-keygen \
    pinentry-curses-ss pinentry-doc \
    podman podman-doc podman-fish-completion \
    podman-remote \
    procs procs-doc procs-fish-completion \
    ripgrep ripgrep-doc ripgrep-fish-completion \
    sed-doc \
    sudo \
    shadow \
    starship \
    topgrade topgrade-doc topgrade-fish-completion \
    tree tree-doc \
    unzip unzip-doc \
    vim vim-doc vimdiff \
    wget wget-doc \
    wipe wipe-doc \
    xh xh-doc xh-fish-completion \
    yq-go yq-go-fish-completion \
    zip zip-doc

COPY --chmod=644 ["config/fish/conf.d/*", "/etc/fish/conf.d/"]
COPY --chmod=644 ["config/fish/functions/*", "/etc/fish/functions/"]

RUN \
    wget -qO- https://github.com/zyedidia/eget/releases/download/v${EGET_VERSION}/eget-${EGET_VERSION}-linux_amd64.tar.gz | \
    tar xzvf - -C /usr/local/bin/ --strip-components 1 --exclude '*/LICENSE' --exclude '*/README.md' && \
    mkdir -p /usr/local/share/man/man1 && \
    mv /usr/local/bin/eget.1 /usr/local/share/man/man1/ && \
    echo '%wheel ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/wheel-nopasswd && \
    sed -ri 's|^(root:)(.*)/bin/sh|\1\2/usr/bin/fish|' /etc/passwd

RUN \
    eget tealdeer-rs/tealdeer --tag ${TLDR_TAG} --to /usr/local/bin/ && \
    ln -s /usr/local/bin/tealdeer /usr/local/bin/tldr

ENTRYPOINT [ "" ]
CMD [ "/usr/bin/fish" ]
